name: 'Create project card'
description: 'Creates a project card on a Github project board based on an Github event.'
author: 'steffektif'
inputs:
  column_id:
    description: 'The id of the project column where the card should be created.'
    required: true
  github_token:
    description: 'Auth token to call the GitHub REST API'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
